apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-miku
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-miku
    app.kubernetes.io/part-of: integ-app-ifpb
  name: hacbs-test-project-miku
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-miku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-miku
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-qcox-tenant/integ-app-ifpb/hacbs-test-project-miku@sha256:76937c933807da51f06dddedffad6eba71e51f0f370682512edfa3b7bb785790
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
